on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: ''

name: Build and Release apk (Manual)
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.8'
      - run: flutter pub get
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > android/app/upload-keystore.jks
          echo $KEY_PROPERTIES | base64 -d > android/key.properties
      - run: flutter build apk --split-per-abi
      - run: mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/ConningTower-${{ inputs.tag }}-arm64-v8a-release.apk
      - run: mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/ConningTower-${{ inputs.tag }}-armeabi-v7a-release.apk
      - run: mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/ConningTower-${{ inputs.tag }}-x86_64-release.apk
      - name: Create Release
        uses: ncipollo/release-action@v1.11.2
        with:
          allowUpdates: true
          tag: ${{ inputs.tag }}
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New Release is update: 
            https://github.com/AndyZhuAZ/conning_tower/releases/tag/${{ inputs.tag }}
