on:
  push:
    tags:
      - "v*"

name: Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Setup Java JDK
          uses: actions/setup-java@v3.7.0
          with:
            java-version: "12.x"
            distribution: temurin
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.8'
      - run: flutter doctor -v
      - run: flutter pub get
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > android/app/upload-keystore.jks
          echo $KEY_PROPERTIES | base64 -d > android/key.properties
      - run: flutter build apk --split-per-abi
      - run: mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/ConningTower-${{ steps.version.outputs.version }}-arm64-v8a-release.apk
      - run: mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/ConningTower-${{ steps.version.outputs.version }}-armeabi-v7a-release.apk
      - run: mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/ConningTower-${{ steps.version.outputs.version }}-x86_64-release.apk
      - name: Create Release
        uses: ncipollo/release-action@v1.11.2
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New Release is update: 
            https://github.com/AndyZhuAZ/conning_tower/releases/tag/${{ steps.version.outputs.version }}
